# Default Configuration file for NyaaPantsu
# PLEASE, do NOT change default_config.yml, create your own config.yml

# Host of server
host: localhost
# Version of the app
version: "1.1.0-mogu"
# port of server
port: 9999
# database type
db_type: sqlite3
# DBParams will be directly passed to Gorm, and its internal structure depends on the dialect for each db type
db_params: ./nyaa.db?cache_size=50
# logmode for database
db_logmode: default
# Environment should be one of: DEVELOPMENT, TEST, PRODUCTION
environment: DEVELOPMENT
# AuthTokenExpirationDay : Number of Days for token expiration when logged in
auth_token_expiration: 1000
# EnableSecureCSRF : Enable CSRF https mode : True if website support https, false otherwise (eg. testing locally: false)
enable_secure_csrf: true
description_length: 10000
comment_length: 2000
# the default config for web addresses
web_address:
  # Nyaa : Origin of the website
  nyaa: https://mogu.holopirates.moe
  # Sukebei : Origin of the sukebei website
  sukebei: soon_maybe
  # Status : Origin of the status website
  status: soon_maybe
# the default config for session cookies
cookies:
  # DomainName : The host domain so the cookies can be shared across subdomains
  domain_name: holopirates.moe
  # MaxAge : The expiration time of sessions cookies in seconds (default: 7 days)
  max_age: 604800
  # HashKey : 64 byte key used to authenticate cookies using HMAC. Leave blank for a random key after each restart.
  hash_key:
  # EncryptionKey : 32 byte key used to encrypt values. Leave blank for a random key after each restart.
  encryption_key:
# the default config for bittorrent scraping
scraper:
  addr: :9999
  workers: 4
  interval: 3600
  trackers:
    - {url: "udp://tracker.holopirates.moe:1337/announce", name: holopirates.moe}
# StatScrapingFrequency : On-demand stat scraping JS will only be loaded if the stats have been scraped X hours ago or higher
  stat_scraping_frequency: 48
# StatScrapingFrequencyUnknown : On-demand stat scraping for unknown torrents JS will only be loaded if the stats have been scraped X hours ago or higher
  stat_scraping_frequency_unknown: 1
# MaxStatScrapingFrequency : On-demand stat scraping can only be called every X minutes, to prevent abuse of the /stats/:id route
  max_stat_scraping_frequency: 5
# MaxStatScrapingFrequencyUnknown : On-demand stat scraping for unknown torrents can only be called every X minutes
  max_stat_scraping_frequency_unknown: 2
#  Default config for upload
upload:
  # The following token/accounts are used when an user wants to upload to another website
  # but doesn't have his own API token.
  anidex_api_token:
  # TokyoTosho : Be aware that file upload doesn't work with the host (only url upload)
  # so you need to enable users to download without ddos protection
  tokyot_api_token:
  # Nyaa.Si : we need a username and a password for the account upload, please use a difficult one! 
  nyaasi_username:
  nyaasi_password:
# UploadsDisabled : Disable uploads for everyone except below
  uploads_disabled: false
# AdminsAreStillAllowedTo : Enable admin torrent upload even if UploadsDisabled is true
  admins_are_still_allowed_to: true
# TrustedUsersAreStillAllowedTo : Enable trusted users torrent upload even if UploadsDisabled is true
  trusted_users_are_still_allowed_to: true
# Config by default for the cache
cache:
  dialect: nop
# Size by default for the cache
  size: 1024
search:
  enable_es: true
# default search analyzer for ES
  es_analyze: nyaapantsu_search_analyzer
# default search index for ES
  es_index: nyaapantsu
# Name of the type in the es mapping
  es_type: torrents
# Default configuration for i2p
#i2p:
#  name:
#  addr:
#  keyfile:
# Default configuration for metainfofetcher
metainfo_fetcher:
  queue_size: 10
  timeout: 120
  max_days: 90
  base_fail_cooldown: 1800
  max_fail_cooldown: 172800
  wake_up_interval: 300
# limits are in KiB, zero means no limit
  upload_rate_limit: 1024
  download_rate_limit: 1024
  fetch_new_torrents_only: true
i18n:
# Default configuration for translation directory
  directory: translations
# Default configuration for language
  default_language: en-us
torrents:
# TorrentStatus : Config of different status id for torrents
  status: [true, true, true, true, true, true]
# TorrentSukebeiCategories : Config for Sukebei categories
  sukebei_categories: {}
# TorrentCleanCategories : Config for Site categories
  clean_categories:
    {
      "1_": "unarchived",
      "1_1": "unarchived_karaoke",
      "1_2": "unarchived_copyright",
      "1_3": "unarchived_yab",
      "2_": "paid",
      "2_1": "paid_membership",
      "2_2": "paid_voice_pack",
      "2_3": "paid_concert",
      "2_4": "paid_songs",
    }
    # EnglishOnlyCategories : Which categories will only accept English torrents
  english_only_categories: []
# NonEnglishOnlyCategories : Which categories will only accept non-English torrents
  non_english_only_categories: []
# AdditionalLanguages : Which languages are available for selection when uploading a torrent, aside from
# the ones we have translations.
  additional_languages: []
# TorrentFileStorage : Path to default torrent storage location (eg /var/www/wherever/you/want)
torrents:
# GenerationClientPort : Port used by the torrent client created during torrent generation
  generation_client_port: 50006
# FileStorage : Location of folder that will contain generated torrent files
  filestorage: ./downloads/
# TorrentStorageLink : Url of torrent file download location (eg https://your.site/somewhere/%s)
  storage_link: /download/%s
# TorrentCacheLink : Url of torrent site cache
  cache_link: #http://anicache.com/torrent/%s.torrent
  trackers:
# Trackers : Default trackers supported
    default:
      - udp://tracker.holopirates.moe:1337/announce
      - udp://tracker.coppersurfer.tk:6969
      - udp://tracker.zer0day.to:1337/announce
      - udp://tracker.leechers-paradise.org:6969
      - udp://explodie.org:6969
      - udp://tracker.opentrackr.org:1337
      - udp://tracker.internetwarriors.net:1337/announce
      - http://mgtracker.org:6969/announce
      - udp://ipv6.leechers-paradise.org:6969/announce
      - http://nyaa.tracker.wf:7777/announce
      - http://sukebei.tracker.wf:7777/announce
      - http://tracker.anirena.com:80/announce
      - http://anidex.moe:6969/announce
# NeededTrackers : Array indexes of Trackers for needed tracker in a torrent file
    needed:
      - 0
      - 12
    dead:
      - ://open.nyaatorrents.info:6544
      - ://tracker.openbittorrent.com:80
      - ://tracker.publicbt.com:80
      - ://stats.anisource.net:2710
      - ://exodus.desync.com
      - ://open.demonii.com:1337
      - ://tracker.istole.it:80
      - ://tracker.ccc.de:80
      - ://bt2.careland.com.cn:6969
      - ://announce.torrentsmd.com:8080
      - ://open.demonii.com:1337
      - ://tracker.btcake.com
      - ://tracker.prq.to
      - ://bt.rghost.net
# TorrentOrder : Default sorting field for torrents
  order: date
# TorrentSort : Default sorting order for torrents
  sort: DESC
  tags:
# Torrent Tag Max weight for automatic system approval
    max_weight: 100.00
# Default tags that have no type, will be saved in AcceptedTags field
    default: tags
# Array of tag types allowed for now
    types:
      # - name: anidbid
      #   field: AnidbID
      #   defaults:
      #     - db
      # - name: vndbid
      #   field: VndbID
      # - name: dlsite
      #   field: Dlsite
      # - name: vgmdbid
      #   field: VgmdbID
      - name: youtubeid
        field: YoutubeID
      - name: videoquality
        field: VideoQuality
        defaults:
          - bluray
          - full_hd
          - hd
          - sd
users:
  default_notifications_settings: {"new_torrent": true, "new_torrent_email": false, "new_comment": true, "new_comment_email": false, "new_responses": false, "new_responses_email": false, "new_follower": false, "new_follower_email": false, "followed": false, "followed_email": false}
navigation:
  torrents_per_page: 50
  max_torrents_per_page: 500
log:
# AccessLogFilePath : Path to logs access
  access_log_filepath: log/access
# AccessLogFileExtension : Extension for log file
  access_log_fileextension: .txt
# AccessLogMaxSize : Size max for a log file in megabytes
  access_log_max_size: 5
# AccessLogMaxBackups : Number of file for logs
  access_log_max_backups: 7
# AccessLogMaxAge : Number of days that we keep logs
  access_log_max_age: 30
# ErrorLogFilePath : Path to log errors
  error_log_filepath: log/error
# ErrorLogFileExtension : Extension for log file
  error_log_fileextension: .json
# ErrorLogMaxSize : Size max for a log file in megabytes
  error_log_max_size: 10
# ErrorLogMaxBackups : Number of file for logs
  error_log_max_backups: 7
# ErrorLogMaxAge : Number of days that we keep logs
  error_log_max_age: 30
email:
# SendEmail : Enable Email
  send_email: false
# EmailFrom : email address by default
  from: donotrespond@nyaa.pantsu.cat
# EmailTestTo : when testing to who send email
  test_to:
# EmailHost : Host of mail server
  host: localhost
# EmailUsername : Username needed for the connection
  username:
# EmailPassword : Password needed for the connection
  password:
# EmailPort : Mail Server port
  port: 465
# EmailTimeout : Timeout for waiting server response
  timeout: 10000000000
models:
# LastOldTorrentID is the highest torrent ID that was copied from the original Nyaa
  last_old_torrent_id: 923000
# TorrentsTableName : Name of torrent table in DB
  torrents_table_name: torrents
# ReportsTableName : Name of torrent report table in DB
  reports_table_name: torrent_reports
# CommentsTableName : Name of comments table in DB
  comments_table_name: comments
# UploadsOldTableName : Name of uploads table in DB
  uploads_old_table_name: user_uploads_old
# FilesTableName : Name of files table in DB
  files_table_name: files
# NotificationTableName : Name of notifications table in DB
  notifications_table_name: notifications
# ActivitiesTableName : Name of activities log table in DB
  activities_table_name: activities
# NotificationTableName : Name of scrape table in DB
  scrape_table_name: scrape
#Default themes
default_theme:
  theme: okayu
  dark: tomorrow
  forced:
  #Put a theme name in forced to force it for everyone
